apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homarr-http
spec:
  parentRefs:
  - name: homarr
    sectionName: http
  rules:
  - backendRefs:
    - name: homarr
      port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homarr-https
spec:
  parentRefs:
  - name: homarr
    sectionName: https
  rules:
  - backendRefs:
    - name: homarr
      port: 3000
