apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - grove-cluster.yaml
  - sbux-oracle-db.yaml
  - pg-migrator-secret.yaml
  - service-lb.yaml
  - authentik-app.yaml
  - authentik-db.yaml